CREATE DATABASE IF NOT EXISTS mobile_laptop_analysis;
DROP DATABASE IF EXISTS mobile_laptop_analysis;
CREATE DATABASE mobile_laptop_analysis;
USE mobile_laptop_analysis;
select * from products;
SELECT COUNT(*) AS total_products FROM products;
select * from customers;
select * from orders;
select * from returns;
select * from reviews;
DROP TABLE products;
SELECT COUNT(*) FROM products;
SELECT COUNT(*) FROM customers;
SELECT COUNT(*) FROM orders;
SELECT COUNT(*) FROM reviews;
SELECT COUNT(*) FROM returns;
SELECT *FROM products WHERE  category = 'Mobile';
select * from products where rating > 4.5;
select Product_Name,Brand,Price_INR from products;
select Product_Name from products;
